#!/usr/bin/python
import sys
import json
from jsonrpc import ServiceProxy

dbid=sys.argv[1]
changeFile=sys.argv[2]

f=open(changeFile, 'r')
s=f.read()
f.close()

changes=json.loads(s)

s=ServiceProxy('http://freefall.blanu.net/document')
print s.modify(dbid, changes)
